#!/bin/bash

set -ex

PRESET=${2:-minSizeRel}
OUTDIR="build/"$(basename ${1})"/libpqcrystals-mldsa-lowram"

rm -rf $OUTDIR
mkdir -p $OUTDIR

./buildit-core $1 $PRESET 44 ${@:3}
./buildit-core $1 $PRESET 65 ${@:3}
./buildit-core $1 $PRESET 87 ${@:3}

cp build/$(basename ${1})/libpqcrystals-mldsa-*-lowram/*.a $OUTDIR/
